# Generated by Django 4.2.16 on 2024-10-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
    ]
