# Generated by Django 4.2.16 on 2024-10-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20241018_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoServicio',
        ),
    ]
