# Generated by Django 4.2.16 on 2024-11-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_delete_productoservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id_producto_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto_serv', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_servicios', to='proveedor.proveedor')),
            ],
        ),
    ]
