# Generated by Django 4.2.16 on 2024-11-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_productoservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_servicios', to='proveedor.proveedor'),
        ),
    ]
