# Generated by Django 4.2.16 on 2024-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0005_alter_productoservicio_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoservicio',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos_servicios',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='proveedor.productoservicio'),
        ),
    ]
