# Generated by Django 4.2.16 on 2024-10-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellidos_cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('documento_cli', models.CharField(max_length=11)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('apellidos_proveedor', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_docum', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_doc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id_producto_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto_servicio', models.CharField(max_length=100)),
                ('proveedores', models.ManyToManyField(related_name='productos', to='sistemaiv.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('preciounidadcompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preciounidadventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_orden_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Recibido', 'Recibido')], default='Pendiente', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(default='', max_length=11)),
                ('fecha_emision', models.DateField()),
                ('precio_total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actividad_comercial', models.CharField(default='Comercio al por menor de computadores, equipos periféricos y equipo de telecomunicaciones.', max_length=255)),
                ('nit', models.CharField(default='700668550-5', max_length=15)),
                ('nombre_negocio', models.CharField(default='TEGNOFACIL', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.cliente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('precio_total_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_unidad_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.categoria')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unidad_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_docum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.tipodocumento'),
        ),
    ]
