# Generated by Django 4.2.16 on 2024-10-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaiv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.factura')),
            ],
        ),
        migrations.CreateModel(
            name='TipoNota',
            fields=[
                ('id_tipo_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nom_nota', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.nota')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.producto')),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='productos',
            field=models.ManyToManyField(through='sistemaiv.ProductoNota', to='sistemaiv.producto'),
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaiv.tiponota'),
        ),
    ]
