# Generated by Django 4.2.16 on 2024-11-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='productos',
        ),
        migrations.AlterField(
            model_name='productonota',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='notas.nota'),
        ),
    ]
