# Generated by Django 4.2.16 on 2024-10-19 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20241018_1813'),
        ('Devolucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
