# Generated by Django 4.2.16 on 2024-10-18 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(default='', max_length=11)),
                ('fecha_emision', models.DateField()),
                ('precio_total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actividad_comercial', models.CharField(default='Comercio al por menor de computadores, equipos periféricos y equipo de telecomunicaciones.', max_length=255)),
                ('nit', models.CharField(default='700668550-5', max_length=15)),
                ('nombre_negocio', models.CharField(default='TEGNOFACIL', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unidad_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
